### ISSUE TITLE
超过8个汉字的长句只能输出后8个字

### ISSUE THREAD

**Issue by inactive0v0** [k9yyy/dead_by_unicode#1]
![qq 20190309004301](https://user-images.githubusercontent.com/28744819/54042113-54b59700-4204-11e9-8144-8e96782300cc.jpg)
输入：**道路**千万条安全第一条
输出：千万条安全第一条
改变字符串，结果相同；小于8个字的字符串没有问题。
总感觉是哪里的buffer满了导致的

**Comment by k9yyy** [comment]
好像必须输入得足够慢才行，已在 1b04eb10d005af7274857c454e8923dafda55aaa 中增大了默认按键延时设定。

推测的原因：Windows默认的按键缓存队列长100，而每个字需要按键6次，每次按下和松开两个事件共12次事件，所以8个字之后队列满了，导致前面的被顶掉。

（缓存队列大小设定在注册表里：`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\kbdclass\Parameters\KeyboardDataQueueSize`，供参考）
